/**
 * Master catalog of every data source CarCheck can query.
 * Seeds the source_registry table. Total: 80+ sources across 21 categories.
 *
 * Convention for `key`:
 *   - mx_fed_<name>       — Mexican federal
 *   - mx_st_<estado>_<x>  — Mexican state portals
 *   - mx_judicial_<x>     — state Fiscalías
 *   - mx_env_<x>          — emissions / verificación
 *   - mx_aduana_<x>       — customs / import
 *   - usa_fed_<name>      — US federal
 *   - usa_st_<state>_<x>  — US state DMV / records
 *   - usa_private_<name>  — US private providers
 *   - oem_<brand>         — OEM owner / recall portals
 *   - mkt_<region>_<x>    — marketplaces / listings
 *   - auction_<name>      — auction houses
 *   - intl_<name>         — international
 */

import type { NewSourceRegistryEntry } from '../schema/source-registry';

export const sourceRegistrySeed: NewSourceRegistryEntry[] = [
  // ─────────────────────────────────────────────────────────────────
  // MX FEDERAL (Tier 1 core)
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'mx_fed_repuve',
    name: 'REPUVE',
    description: 'Registro Público Vehicular — robo, NIV, placa, holograma, institución emplacadora',
    country: 'mx_federal',
    category: 'theft',
    accessMethod: 'scraping_captcha',
    baseUrl: 'https://www2.repuve.gob.mx:8443/ciudadania/',
    requiresVin: true,
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 8000,
    timeoutMs: 20000,
    costUsdPerCall: '0.0500',
    cacheTtlSeconds: 604800,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
    legalNotes: 'SSPC custodia; consulta ciudadana permitida',
  },
  {
    key: 'mx_fed_ocra_amis',
    name: 'OCRA / AMIS',
    description: 'Aseguradoras MX (23 carriers) + cruce INTERPOL — robo y recuperación',
    country: 'mx_federal',
    category: 'theft',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.ocra.com.mx/',
    requiresVin: true,
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 1500,
    costUsdPerCall: '0.1500',
    cacheTtlSeconds: 86400,
    isEnabled: false,
    isTier1: true,
    runsOn: 'vercel',
    legalNotes: 'Requiere convenio con AMIS',
  },
  {
    key: 'mx_fed_rug',
    name: 'RUG (Registro Único de Garantías Mobiliarias)',
    description: 'Prendas / gravámenes activos sobre bienes muebles incluyendo vehículos',
    country: 'mx_federal',
    category: 'liens_finance',
    accessMethod: 'scraping',
    baseUrl: 'https://www.rug.gob.mx',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0.0200',
    cacheTtlSeconds: 604800,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
    legalNotes: 'Consulta pública gratuita (Sec. Economía)',
  },
  {
    key: 'mx_fed_sat_cfdi',
    name: 'SAT CFDI Validator',
    description: 'Verifica autenticidad y vigencia de factura CFDI por UUID + RFC',
    country: 'mx_federal',
    category: 'specs_decode',
    accessMethod: 'scraping',
    baseUrl: 'https://verificacfdi.facturaelectronica.sat.gob.mx/',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'vercel',
    legalNotes: 'Servicio público SAT',
  },
  {
    key: 'mx_fed_amda',
    name: 'AMDA Papel Seguridad',
    description: 'Verifica autenticidad de factura de agencia por QR code AMDA',
    country: 'mx_federal',
    category: 'specs_decode',
    accessMethod: 'scraping',
    baseUrl: 'https://www.amda.mx/factura-amda/',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
    legalNotes: 'Convenio AMDA recomendado a futuro',
  },
  {
    key: 'mx_aduana_anam_quick',
    name: 'ANAM Pediment Quick Query',
    description: 'Verifica pediment de importación de vehículo — crítico para autos chocolate',
    country: 'mx_federal',
    category: 'customs_import',
    accessMethod: 'scraping',
    baseUrl: 'https://www.anam.gob.mx/consulta-rapida-de-pedimentos-de-vehiculos-y-contenedores/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 7776000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
    legalNotes: 'Informativo (Art. 146 LA); respetar TOS',
  },
  {
    key: 'mx_aduana_anam_regularizacion',
    name: 'ANAM Regularización Autos Usados',
    description: 'Folio de regularización bajo decretos 2022-2025 para chocolate cars',
    country: 'mx_federal',
    category: 'customs_import',
    accessMethod: 'scraping',
    baseUrl: 'https://www.anam.gob.mx/importaciones-definitivas-de-automoviles-usados-regularizacion/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 7776000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mx_aduana_vucem',
    name: 'VUCEM',
    description: 'Ventanilla Única — pediment completo (DODA, importer, CAAT)',
    country: 'mx_federal',
    category: 'customs_import',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.ventanillaunica.gob.mx/vucem/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 7776000,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
    legalNotes: 'Requiere e.firma + RFC',
  },
  {
    key: 'mx_fed_profeco_alertas',
    name: 'PROFECO Alertas al Consumidor',
    description: 'Base oficial de recalls MX por marca, modelo, rango de VINs',
    country: 'mx_federal',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://alertas.gob.mx/',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mx_fed_sct',
    name: 'SCT/SICT — Autotransporte Federal',
    description: 'Vehículos pesados federales (carga/pasaje), permisos, ITP',
    country: 'mx_federal',
    category: 'specs_decode',
    accessMethod: 'scraping',
    baseUrl: 'https://www.sct.gob.mx',
    requiresPlate: true,
    acceptsEither: false,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'mx_fed_sesnsp_stats',
    name: 'SESNSP Incidencia Delictiva',
    description: 'Estadística de robo de vehículos por municipio (contexto)',
    country: 'mx_federal',
    category: 'theft',
    accessMethod: 'api_free',
    baseUrl: 'https://www.gob.mx/sesnsp',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 1500,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: false,
    runsOn: 'vercel',
  },

  // ─────────────────────────────────────────────────────────────────
  // MX ESTATAL — 32 entidades
  // ─────────────────────────────────────────────────────────────────
  ...buildMxStateSources(),

  // ─────────────────────────────────────────────────────────────────
  // MX VERIFICACIÓN AMBIENTAL
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'mx_env_cdmx_verificentros',
    name: 'CDMX Verificentros — Historial',
    description: 'Historial completo de verificación vehicular CDMX (odómetro + holograma)',
    country: 'mx_state',
    stateCode: 'CDMX',
    category: 'emissions',
    accessMethod: 'scraping',
    baseUrl: 'http://smahologramas.dsinet.com.mx/ConsultaVerificaciones/',
    requiresPlate: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
    legalNotes: 'Señal de mayor valor por vehículo en CDMX',
  },
  {
    key: 'mx_env_edomex_verificacion',
    name: 'EdoMex Verificación Vehicular',
    description: 'Historial verificación EdoMex por placa',
    country: 'mx_state',
    stateCode: 'MEX',
    category: 'emissions',
    accessMethod: 'scraping',
    baseUrl: 'https://sma.edomex.gob.mx/verificacion-vehicular',
    requiresPlate: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mx_env_cdmx_doble_cero',
    name: 'Holograma Doble Cero (CDMX)',
    description: 'Listado oficial de vehículos con holograma 00 (más limpios)',
    country: 'mx_state',
    stateCode: 'CDMX',
    category: 'emissions',
    accessMethod: 'scraping',
    baseUrl: 'https://verificacionvehicular.sedema.cdmx.gob.mx/Listado/',
    requiresPlate: true,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'mx_env_jalisco_verificacion',
    name: 'Jalisco Verificación',
    description: 'Programa verificación responsable AMG',
    country: 'mx_state',
    stateCode: 'JAL',
    category: 'emissions',
    accessMethod: 'scraping',
    baseUrl: 'https://verificacion.semadet.jalisco.gob.mx',
    requiresPlate: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },

  // ─────────────────────────────────────────────────────────────────
  // MX JUDICIAL (Fiscalías top 6 por robo)
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'mx_judicial_fgjem',
    name: 'Fiscalía EdoMex — Vehículos Robados',
    description: 'Reporte de robo y galería de recuperados EdoMex',
    country: 'mx_state',
    stateCode: 'MEX',
    category: 'theft',
    accessMethod: 'scraping',
    baseUrl: 'http://fgjem.edomex.gob.mx/reporte-robo',
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mx_judicial_fgjcdmx',
    name: 'Fiscalía CDMX — Vehículos Robados',
    description: 'Robo vehicular CDMX',
    country: 'mx_state',
    stateCode: 'CDMX',
    category: 'theft',
    accessMethod: 'scraping',
    baseUrl: 'https://www.fgjcdmx.gob.mx/',
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mx_judicial_fge_jalisco',
    name: 'Fiscalía Jalisco',
    description: 'Robo vehicular Jalisco',
    country: 'mx_state',
    stateCode: 'JAL',
    category: 'theft',
    accessMethod: 'scraping',
    baseUrl: 'https://fge.jalisco.gob.mx/',
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'mx_judicial_fge_nl',
    name: 'Fiscalía Nuevo León',
    description: 'Robo vehicular NL',
    country: 'mx_state',
    stateCode: 'NL',
    category: 'theft',
    accessMethod: 'scraping',
    baseUrl: 'https://fiscalianl.gob.mx/',
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'mx_judicial_fge_puebla',
    name: 'Fiscalía Puebla',
    description: 'Robo vehicular Puebla',
    country: 'mx_state',
    stateCode: 'PUE',
    category: 'theft',
    accessMethod: 'scraping',
    baseUrl: 'https://fiscalia.puebla.gob.mx/',
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'mx_judicial_fge_veracruz',
    name: 'Fiscalía Veracruz',
    description: 'Robo vehicular Veracruz',
    country: 'mx_state',
    stateCode: 'VER',
    category: 'theft',
    accessMethod: 'scraping',
    baseUrl: 'https://fiscaliaveracruz.gob.mx/',
    requiresPlate: true,
    acceptsEither: true,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },

  // ─────────────────────────────────────────────────────────────────
  // MX FINANCIERO (Tier 3 — requires partnership)
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'mx_fin_buro_credito',
    name: 'Buró de Crédito — Vehículos',
    description: 'Financiamiento vehicular y reposesiones (por RFC del titular)',
    country: 'mx_federal',
    category: 'liens_finance',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.burodecredito.com.mx',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '0.5000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
    legalNotes: 'Requiere convenio SOFOM, regulado CONDUSEF',
  },
  {
    key: 'mx_fin_circulo_credito',
    name: 'Círculo de Crédito — Vehículos',
    description: 'Segunda SIC mexicana (por RFC)',
    country: 'mx_federal',
    category: 'liens_finance',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.circulodecredito.com.mx/home',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '0.5000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },

  // ─────────────────────────────────────────────────────────────────
  // USA FEDERAL
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'usa_fed_nhtsa_vpic',
    name: 'NHTSA vPIC',
    description: 'Decodificación VIN oficial — marca, modelo, año, planta, especificaciones',
    country: 'usa_federal',
    category: 'specs_decode',
    accessMethod: 'api_free',
    baseUrl: 'https://vpic.nhtsa.dot.gov/api/',
    docsUrl: 'https://vpic.nhtsa.dot.gov/api/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 800,
    costUsdPerCall: '0',
    cacheTtlSeconds: 31536000,
    isEnabled: true,
    isTier1: true,
    runsOn: 'vercel',
  },
  {
    key: 'usa_fed_nhtsa_recalls',
    name: 'NHTSA Recalls',
    description: 'Recalls abiertos por VIN',
    country: 'usa_federal',
    category: 'recalls',
    accessMethod: 'api_free',
    baseUrl: 'https://api.nhtsa.gov/recalls/recallsByVehicle',
    docsUrl: 'https://www.nhtsa.gov/recalls',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 1000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'vercel',
  },
  {
    key: 'usa_fed_nmvtis_vinaudit',
    name: 'NMVTIS via VinAudit',
    description: 'Title brands, salvage, junk, robo histórico USA — 50 estados',
    country: 'usa_federal',
    category: 'title_brands',
    accessMethod: 'api_paid',
    baseUrl: 'https://api.vinaudit.com/v2',
    docsUrl: 'https://www.vinaudit.com/nmvtis-data',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '2.4900',
    cacheTtlSeconds: 1209600,
    isEnabled: true,
    isTier1: true,
    runsOn: 'vercel',
  },
  {
    key: 'usa_fed_nicb_vincheck',
    name: 'NICB VINCheck',
    description: 'Robo + salvage USA (5/día/IP)',
    country: 'usa_federal',
    category: 'theft',
    accessMethod: 'scraping_captcha',
    baseUrl: 'https://www.nicb.org/vincheck',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 8000,
    costUsdPerCall: '0.0500',
    cacheTtlSeconds: 1209600,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
    legalNotes: 'Rate limit 5/día/IP — necesita rotación proxies',
  },
  {
    key: 'usa_fed_epa_certification',
    name: 'EPA Certification Lookup',
    description: 'Certificate of Conformity (US vs CA emissions standards)',
    country: 'usa_federal',
    category: 'emissions',
    accessMethod: 'scraping',
    baseUrl: 'https://dis.epa.gov/otaqpub/',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 31536000,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },

  // ─────────────────────────────────────────────────────────────────
  // USA PRIVATE — Vehicle history aggregators
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'usa_private_autocheck',
    name: 'Experian AutoCheck',
    description: 'Title, accidents, frame, mileage, auction; AutoCheck Score',
    country: 'usa_private',
    category: 'accidents',
    accessMethod: 'api_paid',
    baseUrl: 'https://www.experian.com/automotive/autocheck-business',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2500,
    costUsdPerCall: '1.5000',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_carfax_mx',
    name: 'Carfax MX (Carinfo)',
    description: 'Datos Carfax con foco MX vía Carinfo',
    country: 'usa_private',
    category: 'accidents',
    accessMethod: 'partner_api',
    baseUrl: 'https://carfax.mx',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '5.0000',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
    legalNotes: 'Posible partnership; también competidor directo',
  },
  {
    key: 'usa_private_bumper',
    name: 'Bumper',
    description: 'NMVTIS + listing + service + accident',
    country: 'usa_private',
    category: 'accidents',
    accessMethod: 'api_paid',
    baseUrl: 'https://www.bumper.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '0.5000',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_epicvin',
    name: 'EpicVIN',
    description: 'NMVTIS + sales history + market value',
    country: 'usa_private',
    category: 'accidents',
    accessMethod: 'api_paid',
    baseUrl: 'https://epicvin.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2500,
    costUsdPerCall: '0.7500',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_clearvin',
    name: 'ClearVin',
    description: 'NMVTIS + emission test records lookup',
    country: 'usa_private',
    category: 'accidents',
    accessMethod: 'api_paid',
    baseUrl: 'https://www.clearvin.com',
    docsUrl: 'https://www.clearvin.com/en/api-subscribers/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2500,
    costUsdPerCall: '0.6000',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_marketcheck_history',
    name: 'MarketCheck VIN History',
    description: '5B+ historical US/CA listings since 2015 — price + odometer history per VIN',
    country: 'usa_private',
    category: 'listings',
    accessMethod: 'api_paid',
    baseUrl: 'https://api.marketcheck.com',
    docsUrl: 'https://docs.marketcheck.com/docs/api/cars/vehicle-history/history-by-vin',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '0.2500',
    cacheTtlSeconds: 604800,
    isEnabled: true,
    isTier1: true,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_vinaudit_market',
    name: 'VinAudit Market Value',
    description: 'Precio de mercado US por VIN',
    country: 'usa_private',
    category: 'market_value',
    accessMethod: 'api_paid',
    baseUrl: 'https://api.vinaudit.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 1500,
    costUsdPerCall: '0.1500',
    cacheTtlSeconds: 604800,
    isEnabled: true,
    isTier1: true,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_carsxe',
    name: 'CarsXE',
    description: 'VIN decoder + history + images + market',
    country: 'usa_private',
    category: 'specs_decode',
    accessMethod: 'api_paid',
    baseUrl: 'https://api.carsxe.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 1500,
    costUsdPerCall: '0.3000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_private_dataone',
    name: 'DataOne Software',
    description: 'OEM specs/trims/options enterprise',
    country: 'usa_private',
    category: 'specs_decode',
    accessMethod: 'api_paid',
    baseUrl: 'https://www.dataonesoftware.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 1500,
    costUsdPerCall: '0.4000',
    cacheTtlSeconds: 31536000,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },

  // ─────────────────────────────────────────────────────────────────
  // USA STATE DMV
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'usa_st_tx_titlecheck',
    name: 'Texas TxDMV Title Check',
    description: 'Title status TX (alta relevancia chocolate cars)',
    country: 'usa_state',
    stateCode: 'TX',
    category: 'title_brands',
    accessMethod: 'scraping',
    baseUrl: 'https://www.txdmv.gov/motorists/buying-or-selling-a-vehicle/title-check-look-before-you-buy',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '3.0000',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'usa_st_ca_smogcheck',
    name: 'California BAR Smog Check History',
    description: 'Historial emisiones CA por VIN/placa',
    country: 'usa_state',
    stateCode: 'CA',
    category: 'emissions',
    accessMethod: 'scraping',
    baseUrl: 'https://www.bar.ca.gov',
    requiresVin: true,
    acceptsEither: true,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 2592000,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'usa_st_fl_titlecheck',
    name: 'Florida FLHSMV Title',
    description: 'Title FL — alto volumen salvage/flood',
    country: 'usa_state',
    stateCode: 'FL',
    category: 'title_brands',
    accessMethod: 'scraping',
    baseUrl: 'https://services.flhsmv.gov',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'railway',
  },

  // ─────────────────────────────────────────────────────────────────
  // USA INSURANCE (Tier 3 — partnership required)
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'usa_ins_iso_claimsearch',
    name: 'ISO ClaimSearch (Verisk)',
    description: '95% claims P&C USA — theft, salvage, BI',
    country: 'usa_private',
    category: 'insurance',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.verisk.com/products/claimsearch/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '3.0000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_ins_lexisnexis_clue',
    name: 'LexisNexis C.L.U.E. Auto',
    description: '7 años de claims insurance por VIN',
    country: 'usa_private',
    category: 'insurance',
    accessMethod: 'partner_api',
    baseUrl: 'https://risk.lexisnexis.com/products/clue-auto',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2500,
    costUsdPerCall: '4.0000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'usa_ins_ccc',
    name: 'CCC Intelligent Solutions',
    description: 'Repair estimates + total-loss decisions',
    country: 'usa_private',
    category: 'insurance',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.cccis.com/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '2.0000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },

  // ─────────────────────────────────────────────────────────────────
  // SUBASTAS
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'auction_copart',
    name: 'Copart Auction History',
    description: 'Salvage/insurance auctions — VIN, fotos, daño, precio',
    country: 'usa_private',
    category: 'auctions',
    accessMethod: 'scraping',
    baseUrl: 'https://www.copart.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 7000,
    costUsdPerCall: '0.5000',
    cacheTtlSeconds: 1209600,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'auction_iaa',
    name: 'IAA (Insurance Auto Auctions)',
    description: 'IAAI salvage auctions con fotos y daño',
    country: 'usa_private',
    category: 'auctions',
    accessMethod: 'scraping',
    baseUrl: 'https://www.iaai.com',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 7000,
    costUsdPerCall: '0.5000',
    cacheTtlSeconds: 1209600,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'auction_manheim',
    name: 'Manheim Market Report',
    description: 'Subasta mayorista dealer — precios MMR + condition reports',
    country: 'usa_private',
    category: 'auctions',
    accessMethod: 'partner_api',
    baseUrl: 'https://developer.manheim.com/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '1.0000',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
    legalNotes: 'Requiere dealer/wholesale account',
  },
  {
    key: 'auction_statvin',
    name: 'Stat.vin (Copart+IAAI aggregator)',
    description: 'Agregador unificado Copart+IAAI',
    country: 'usa_private',
    category: 'auctions',
    accessMethod: 'api_paid',
    baseUrl: 'https://stat.vin',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '1.0000',
    cacheTtlSeconds: 1209600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },

  // ─────────────────────────────────────────────────────────────────
  // OEM RECALL PORTALS
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'oem_toyota',
    name: 'Toyota Owners Recall',
    description: 'Recalls + service campaigns Toyota/Lexus/Scion',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://www.toyota.com/recall/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'oem_gm',
    name: 'GM Owner Center',
    description: 'Chevy / Buick / GMC / Cadillac',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://experience.gm.com/ownercenter/recalls',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'oem_ford',
    name: 'Ford Owner Recalls',
    description: 'Ford / Lincoln safety campaigns',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://www.ford.com/support/recalls/',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'oem_honda',
    name: 'Honda / Acura Owners',
    description: 'Recalls Honda + Acura',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://owners.honda.com/recalls',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'oem_nissan',
    name: 'Nissan Owners',
    description: 'Recalls Nissan / Infiniti',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://owners.nissanusa.com/nowners/vinlookup/vinlookupresults',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'oem_vw',
    name: 'Volkswagen Owners',
    description: 'Recalls VW / Audi / Seat',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://www.vw.com/en/owners/safety-and-recalls.html',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'oem_bmw',
    name: 'BMW Recalls',
    description: 'BMW / MINI recalls',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://www.bmwusa.com/vehicles/bmwvalue/recall-information.html',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'oem_mercedes',
    name: 'Mercedes-Benz Recalls',
    description: 'MB recalls + connected vehicle (con consent)',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://www.mbusa.com/en/owners/recalls',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },
  {
    key: 'oem_stellantis',
    name: 'Stellantis (FCA) Recalls',
    description: 'Chrysler / Jeep / Dodge / Ram / Fiat',
    country: 'oem',
    category: 'recalls',
    accessMethod: 'scraping',
    baseUrl: 'https://www.mopar.com/en-us/care/recall-info.html',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 4000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },

  // ─────────────────────────────────────────────────────────────────
  // CONNECTED CAR / TELEMETRY (consent-based)
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'oem_smartcar',
    name: 'Smartcar Connected Vehicle',
    description: 'Odómetro + ubicación + fuel (con OAuth del dueño)',
    country: 'oem',
    category: 'service_history',
    accessMethod: 'api_paid',
    baseUrl: 'https://api.smartcar.com',
    docsUrl: 'https://smartcar.com/industries/vehicle-history-reports',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '0.5000',
    cacheTtlSeconds: 3600,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
    legalNotes: 'Requiere consent del dueño vía OAuth',
  },

  // ─────────────────────────────────────────────────────────────────
  // MARKETPLACES MX
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'mkt_mx_mercadolibre',
    name: 'Mercado Libre Autos',
    description: 'Listings autos MX',
    country: 'market',
    category: 'listings',
    accessMethod: 'scraping',
    baseUrl: 'https://autos.mercadolibre.com.mx',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0.0200',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mkt_mx_seminuevos',
    name: 'Seminuevos.com',
    description: 'Listings autos MX',
    country: 'market',
    category: 'listings',
    accessMethod: 'scraping',
    baseUrl: 'https://www.seminuevos.com',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0.0200',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mkt_mx_kavak',
    name: 'Kavak Seminuevos',
    description: 'Inventario Kavak con inspección 240 puntos',
    country: 'market',
    category: 'listings',
    accessMethod: 'scraping',
    baseUrl: 'https://www.kavak.com/mx/seminuevos',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0.0200',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: true,
    runsOn: 'railway',
  },
  {
    key: 'mkt_mx_autocosmos',
    name: 'Autocosmos México',
    description: 'Listings nuevos + usados MX',
    country: 'market',
    category: 'listings',
    accessMethod: 'scraping',
    baseUrl: 'https://www.autocosmos.com.mx',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 6000,
    costUsdPerCall: '0.0200',
    cacheTtlSeconds: 86400,
    isEnabled: true,
    isTier1: false,
    runsOn: 'railway',
  },

  // ─────────────────────────────────────────────────────────────────
  // IMAGEN / REVERSE SEARCH
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'image_serpapi_lens',
    name: 'Google Lens via SerpAPI',
    description: 'Reverse image search para listings',
    country: 'international',
    category: 'listings',
    accessMethod: 'api_paid',
    baseUrl: 'https://serpapi.com/google-lens-api',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 5000,
    costUsdPerCall: '0.0100',
    cacheTtlSeconds: 2592000,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },
  {
    key: 'image_tineye',
    name: 'TinEye API',
    description: '77B image index — buscar foto original de listing',
    country: 'international',
    category: 'listings',
    accessMethod: 'api_paid',
    baseUrl: 'https://api.tineye.com',
    requiresVin: false,
    acceptsEither: false,
    typicalLatencyMs: 3000,
    costUsdPerCall: '0.0500',
    cacheTtlSeconds: 2592000,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
  },

  // ─────────────────────────────────────────────────────────────────
  // INTERNATIONAL
  // ─────────────────────────────────────────────────────────────────
  {
    key: 'intl_interpol_smv',
    name: 'INTERPOL Stolen Motor Vehicle DB',
    description: '12M+ international stolen-vehicle records (via OCRA)',
    country: 'international',
    category: 'theft',
    accessMethod: 'partner_api',
    baseUrl: 'https://www.interpol.int/en/Crimes/Vehicle-crime',
    requiresVin: true,
    acceptsEither: false,
    typicalLatencyMs: 2000,
    costUsdPerCall: '0',
    cacheTtlSeconds: 604800,
    isEnabled: false,
    isTier1: false,
    runsOn: 'vercel',
    legalNotes: 'Acceso indirecto vía OCRA',
  },
];

/**
 * Builds source registry entries for all 32 Mexican states.
 * Standard pattern: control vehicular (refrendo / tenencia / adeudos) by plate + last 4-5 of VIN.
 */
function buildMxStateSources(): NewSourceRegistryEntry[] {
  const states: Array<{ code: string; name: string; url: string; tier1?: boolean }> = [
    { code: 'AGS', name: 'Aguascalientes', url: 'https://eservicios2.aguascalientes.gob.mx/' },
    { code: 'BC', name: 'Baja California', url: 'https://tramites.ebajacalifornia.gob.mx/ventanillaunica/tramites/controlvehicular', tier1: true },
    { code: 'BCS', name: 'Baja California Sur', url: 'http://apps.bcs.gob.mx/pedimento/pedimento.php' },
    { code: 'CAMP', name: 'Campeche', url: 'https://finanzas.campeche.gob.mx' },
    { code: 'CHIS', name: 'Chiapas', url: 'https://www.ingresos.haciendachiapas.gob.mx/servicios/adeudo-vehic-OE.asp' },
    { code: 'CHIH', name: 'Chihuahua', url: 'https://www.chihuahua.gob.mx', tier1: true },
    { code: 'COAH', name: 'Coahuila', url: 'https://www.pagafacil.gob.mx/' },
    { code: 'COL', name: 'Colima', url: 'https://secfinanzas.col.gob.mx' },
    { code: 'CDMX', name: 'Ciudad de México', url: 'https://data.finanzas.cdmx.gob.mx/consulta_adeudos', tier1: true },
    { code: 'DGO', name: 'Durango', url: 'https://durango.gob.mx' },
    { code: 'MEX', name: 'Estado de México', url: 'https://sfpya.edomexico.gob.mx/controlv/faces/tramiteselectronicos/cv/portalPublico/ConsultaVigenciaPlaca.xhtml', tier1: true },
    { code: 'GTO', name: 'Guanajuato', url: 'https://refrendo.guanajuato.gob.mx/' },
    { code: 'GRO', name: 'Guerrero', url: 'https://finanzas.guerrero.gob.mx' },
    { code: 'HGO', name: 'Hidalgo', url: 'https://finanzas.hidalgo.gob.mx' },
    { code: 'JAL', name: 'Jalisco', url: 'https://sfp.jalisco.gob.mx/', tier1: true },
    { code: 'MICH', name: 'Michoacán', url: 'https://secfinanzas.michoacan.gob.mx/' },
    { code: 'MOR', name: 'Morelos', url: 'https://hacienda.morelos.gob.mx' },
    { code: 'NAY', name: 'Nayarit', url: 'https://hacienda.nayarit.gob.mx' },
    { code: 'NL', name: 'Nuevo León', url: 'https://www.icvnl.gob.mx/EstadodeCuenta', tier1: true },
    { code: 'OAX', name: 'Oaxaca', url: 'https://www.finanzasoaxaca.gob.mx/' },
    { code: 'PUE', name: 'Puebla', url: 'https://finanzas.puebla.gob.mx', tier1: true },
    { code: 'QRO', name: 'Querétaro', url: 'https://finanzas.queretaro.gob.mx' },
    { code: 'QROO', name: 'Quintana Roo', url: 'https://satq.qroo.gob.mx/controlvehicular/' },
    { code: 'SLP', name: 'San Luis Potosí', url: 'https://finanzas.slp.gob.mx' },
    { code: 'SIN', name: 'Sinaloa', url: 'https://ase.sinaloa.gob.mx' },
    { code: 'SON', name: 'Sonora', url: 'https://cuentaunica.siiafhacienda.gob.mx/expressvehicular/verificacion' },
    { code: 'TAB', name: 'Tabasco', url: 'https://finanzas.tabasco.gob.mx' },
    { code: 'TAMPS', name: 'Tamaulipas', url: 'https://sat.tamaulipas.gob.mx', tier1: true },
    { code: 'TLAX', name: 'Tlaxcala', url: 'https://a-tenenciaonline.sefintlax.gob.mx/TenenciaEnLinea/consultar_tenencia/' },
    { code: 'VER', name: 'Veracruz', url: 'https://www.haciendaveracruz.gob.mx' },
    { code: 'YUC', name: 'Yucatán', url: 'https://reemplacamiento.yucatan.gob.mx/' },
    { code: 'ZAC', name: 'Zacatecas', url: 'https://finanzas.zacatecas.gob.mx' },
  ];

  return states.map((s) => ({
    key: `mx_st_${s.code.toLowerCase()}_control_vehicular`,
    name: `${s.name} — Control Vehicular`,
    description: `Refrendo, tenencia, adeudos y multas — ${s.name}`,
    country: 'mx_state' as const,
    stateCode: s.code,
    category: 'fines_taxes' as const,
    accessMethod: 'scraping_captcha' as const,
    baseUrl: s.url,
    requiresVin: true,
    requiresPlate: true,
    acceptsEither: false,
    typicalLatencyMs: 8000,
    timeoutMs: 20000,
    costUsdPerCall: '0.0500',
    cacheTtlSeconds: 604800,
    isEnabled: true,
    isTier1: s.tier1 ?? false,
    runsOn: 'railway' as const,
    legalNotes: 'Consulta pública estatal; respetar throttling',
  }));
}
